### ISSUE TITLE
where is the confidence-aware loss

### ISSUE THREAD

**Issue by xiaohutongxue-sunny** [luxiaolili/MimicMotion_train#5]
Hello,friend, i explored your codes, i find you did not modify your dataset, and loss based no confidence-aware

**Comment by luxiaolili** [comment]
> Hello,friend, i explored your codes, i find you did not modify your dataset, and loss based no confidence-aware

I'm doing some experiments for the hands mask and the dataset, if the experiment is ready, i will release it

**Comment by xiaohutongxue-sunny** [comment]
thanks for your wonderful work

**Comment by xiaohutongxue-sunny** [comment]
> > Hello,friend, i explored your codes, i find you did not modify your dataset, and loss based no confidence-aware
> 
> I'm doing some experiments for the hands mask and the dataset, if the experiment is ready, i will release it

Thanks for your wonderful work
