### ISSUE TITLE
would you release the dataset prepare code?

### ISSUE THREAD

**Issue by greasebig** [luxiaolili/MimicMotion_train#7]
hello, excellent work. would you release the dataset prepare code?

    video_data/XXXvideo
        |-- imgs
        |-- faces
        |-- lmks
        |-- pose_mask
I don’t quite understand what these refer to.

**Comment by luxiaolili** [comment]
> hello, excellent work. would you release the dataset prepare code?
> 
> ```
> video_data/XXXvideo
>     |-- imgs
>     |-- faces
>     |-- lmks
>     |-- pose_mask
> ```
> 
> I don’t quite understand what these refer to.

I have release the dataset prepare code

**Comment by greasebig** [comment]
amazing and wonderful work! thanks again
