### ISSUE TITLE
a open source dataser name humanvid

### ISSUE THREAD

**Issue by xiaohutongxue-sunny** [luxiaolili/MimicMotion_train#8]
if you are willing to optimizer your research, you can use this open source dataset :https://github.com/zhenzhiwang/HumanVid.
Thanks for you contribution. Appreciation

**Comment by luxiaolili** [comment]
> if you are willing to optimizer your research, you can use this open source dataset :https://github.com/zhenzhiwang/HumanVid. Thanks for you contribution. Appreciation

你有复现很好的结果吗？我发现前几帧能控制住后面就飞了

**Comment by xiaohutongxue-sunny** [comment]
，没有，我目前因为工作原因已经停了，偶尔会收集数据，我准备用 FLUX 加上ControlNet 试试。 就是参考ControlNXet的想法。你有微信吗？ 你发我邮箱747923609@qq.com，我找个时间把我收集的数据分享给你。不过有有部分数据都是没有裁剪的，需要你自己裁剪。

**Comment by luxiaolili** [comment]
> ，没有，我目前因为工作原因已经停了，偶尔会收集数据，我准备用 FLUX 加上ControlNet 试试。 就是参考ControlNXet的想法。你有微信吗？ 你发我邮箱[747923609@qq.com](mailto:747923609@qq.com)，我找个时间把我收集的数据分享给你。不过有有部分数据都是没有裁剪的，需要你自己裁剪。

我也不是工作需求，是我自己感兴趣，一个人在搞，我试过ControlNXet也很难控制训练出它模型的效果，控制不住，他们肯定加了很多额外的数据 wx: wq1443961545

**Comment by greasebig** [comment]
你好。请问下关于Confidence-aware pose guidance的实验效果是怎样的呢？我看到现在的代码还没有这块儿内容，你之前说你还在实验看效果，可以分享一下加了后效果怎样吗？
原论文有两个点，不过你这次更新的代码里也还没有，1. 每个关键点和肢体的颜色乘以其置信度分数，2. 对手部设置阈值得到unmask，只保留置信度分数超过预定义阈值的可靠区域，在损失计算中按一定比例分配更大的权重。
